TECH-134: Create test configuration for "/authorize" endpoint
GovStackWorkingGroup/bb-identity pull request #11
Opened 2023-01-17 12:49 UTC by KarolinaKopacz

Create test configuration for "/authorize" endpoint.

Create test configuration for /authorize endpoint from https://github.com/GovStackWorkingGroup/bb-identity/pull/6 . Identify the critical APIs for Authentication, write the test plan and Cucumber tests, as well as supporting code to run those Cucumber tests.

TICKET: https://govstack-global.atlassian.net/browse/TECH-134

2023-01-18 15:23 UTC, jdub13 approved these changes

2023-01-19 11:51 UTC, mgrochalskisoldevelo commented on examples/mock/mockoon-bbidentity.json
> +              "value": "^openid profile$|^openid$|^profile$|^email$|^address$|^phone$|^office_access$",
Looking at API should be offline_access - not office_access
![image](https://user-images.githubusercontent.com/119664031/213434752-c59544c1-fef4-4fc2-831d-91fe7b0b6e74.png)

2023-01-19 11:51 UTC, mgrochalskisoldevelo commented on examples/mock/mockoon-bbidentity.json
> +              "value": "^openid profile$|^openid$|^profile$|^email$|^address$|^phone$|^office_access$",
the same as above - office_access -> offline_access

2023-01-19 12:03 UTC, mgrochalskisoldevelo commented on test/features/oidc_authorize.feature
> +    Given The user wants to loads JS application, and validates the provided query parameters using oauth-details endpoint
I think it should be ```The user wants to load JS application, and validates the provided query parameters using the oauth-details endpoint```

2023-01-19 12:04 UTC, mgrochalskisoldevelo commented on test/features/oidc_authorize.feature
> +    When The user triggers an action with every required parameters
I think it should be ```The user triggers an action with every required parameter```

2023-01-19 12:06 UTC, mgrochalskisoldevelo commented on test/features/oidc_authorize.feature
> +  Scenario: Successfully loads JS application, and validates the provided query parameters using oauth-details endpoint
maybe ```using the oauth-details endpoint```

2023-01-19 12:07 UTC, mgrochalskisoldevelo commented on test/features/oidc_authorize.feature
> +    Then The user successfully loads JS application, and validates the provided query parameters using oauth-details endpoint
Same as the Scenario:

2023-01-19 12:13 UTC, mgrochalskisoldevelo requested changes
Please take a look at my comments - I mentioned just a few scenarios, the others have the same cases.

2023-01-19 16:29 UTC, mgrochalskisoldevelo approved these changes

2023-01-20 09:42 UTC, dborowiecki approved these changes
All necessary approvals were added, I'll merge the PR.

2023-01-20 09:42 UTC, merged