TECH-140: Create test configuration for "/authorization/oauth-details" endpoint
GovStackWorkingGroup/bb-identity pull request #13
Opened 2023-01-23 16:15 UTC by KarolinaKopacz

Create test configuration for "/authorization/oauth-details" endpoint.

Create test configuration for /authorization/oauth-details endpoint from https://github.com/GovStackWorkingGroup/bb-identity/pull/6.
Identify the critical APIs for Authentication, write the test plan and Cucumber tests, as well as supporting code to run those Cucumber tests.

TICKET: https://govstack-global.atlassian.net/browse/TECH-140

2023-01-26 17:14 UTC, mgrochalskisoldevelo requested changes
As for the bodies we use in request I recommend using: Data Management feature from pactumJS : https://pactumjs.github.io/guides/data-management.html#data-management.
But it is to confirm with the others.

Please take a look at what I mentioned below, maybe I missed something.

From what I see you return an ```invalid_body``` error message, which I could not find in the SWAGGER.
![image](https://user-images.githubusercontent.com/119664031/214899399-48527cb4-9e6f-4e6b-8a35-bedc9aaf8436.png)

Also I can see in successful return example that errors come as ```null```, you are expecting an empty array

2023-01-26 17:20 UTC, mgrochalskisoldevelo requested changes

2023-01-26 17:20 UTC, mgrochalskisoldevelo commented on test/features/support/ui_oauth_details.js
> +        errors: [],
![image](https://user-images.githubusercontent.com/119664031/214903871-c3ee66fb-7056-45b0-923a-f70d082afaa4.png)


seems like ```null``` should be the default value, also to change in mocks
```[] -> null```

2023-01-26 17:20 UTC, mgrochalskisoldevelo commented on test/features/support/ui_oauth_details.js
> +  async () => await errorResultFunction("invalid_body")
![image](https://user-images.githubusercontent.com/119664031/214904245-e32cc90e-f67a-4eb0-bea4-53fa8f72c12c.png)

There is no ```invalid_body``` in errors enum

2023-01-31 13:02 UTC, mgrochalskisoldevelo approved these changes

2023-05-12 10:41 UTC, KarolinaKopacz commented
I'm going to close this PR because endpoint no longer exist in the bb-identity API spec.

2023-05-12 10:41 UTC, closed without merging