TECH-141: Create test configuration for "/authorization/send-otp" endpoint
GovStackWorkingGroup/bb-identity pull request #14
Opened 2023-01-24 16:19 UTC by KarolinaKopacz

Create test configuration for "/authorization/send-otp" endpoint.

Create test configuration for /authorization/oauth-details endpoint from https://github.com/GovStackWorkingGroup/bb-identity/pull/6.
Identify the critical APIs for Authentication, write the test plan and Cucumber tests, as well as supporting code to run those Cucumber tests.

TICKET: https://govstack-global.atlassian.net/browse/TECH-141

2023-02-01 11:11 UTC, mgrochalskisoldevelo requested changes
There is something I'd like to confirm.

![image](https://user-images.githubusercontent.com/119664031/216022363-9b8ec68c-ac64-4a8a-9510-677e2a004e49.png)

The description in response tells us ```null if failed to deliver OTP```
Does it apply to response or messageCode ? @KarolinaKopacz 
To consider is that one of those can come as null

Also added 1 suggestion in the comment.

2023-02-02 08:38 UTC, KarolinaKopacz commented on test/features/support/ui_authorization_send_otp.js
> +  specUIAuthSendOTP = pactum.spec();
Thank you!

2023-02-02 13:30 UTC, mgrochalskisoldevelo requested changes
I left a comment with small issue. Except that LGTM

2023-02-02 13:30 UTC, mgrochalskisoldevelo commented on test/features/support/ui_authorization_send_otp.js
> +  specUIAuthSendOTP.expectResponseTime(1500);
Please change it to 15000. It's an amount in milliseconds

2023-02-02 15:04 UTC, mgrochalskisoldevelo approved these changes
LGTM

2023-05-12 10:41 UTC, KarolinaKopacz commented
I'm going to close this PR because endpoint no longer exist in the bb-identity API spec.

2023-05-12 10:41 UTC, closed without merging