TECH-724: Add fixes to BB-Identity POST /linked-authorization/link-status
GovStackWorkingGroup/bb-identity pull request #41
Opened 2023-05-31 13:11 UTC by KarolinaKopacz

Add fixes to BB-Identity POST /linked-authorization/link-status

Ticket: https://govstack-global.atlassian.net/browse/TECH-724

Corresponding comments from earlier PR:
- https://github.com/GovStackWorkingGroup/bb-identity/pull/32#discussion_r1210069340
- https://github.com/GovStackWorkingGroup/bb-identity/pull/32#discussion_r1210615407
- https://github.com/GovStackWorkingGroup/bb-identity/pull/32#discussion_r1210620153
- https://github.com/GovStackWorkingGroup/bb-identity/pull/32#discussion_r1210628681

2023-06-26 01:33 UTC, vishwa-vyom requested changes

2023-06-26 01:33 UTC, vishwa-vyom commented on test/openAPI/features/wallet_link_status.feature
> +    When Send POST /linked-authorization/link-status request with given X-XSRF-TOKEN header, completed transactionId, linkCode and requestTime
completed transaction id should mean where a transaction has already gone through link-code, authenticate, consent and link auth code

2023-07-27 12:37 UTC, mdulko approved these changes

2023-08-09 13:46 UTC, KarolinaKopacz commented
@vishwa-vyom I tried to add test for this case https://github.com/GovStackWorkingGroup/bb-identity/pull/32#discussion_r1210628681 but there is no good solution for it. I left my comment under your comment

2023-08-29 13:42 UTC, vishwa-vyom approved these changes

2023-08-29 13:47 UTC, merged