TECH-734: Add fixes to POST /linked-authorization/authenticate
GovStackWorkingGroup/bb-identity pull request #47
Opened 2023-06-16 07:57 UTC by mdulko

Add fixes to BB-Identity POST /linked-authorization/authenticate

Ticket: https://govstack-global.atlassian.net/browse/TECH-734

Corresponding comments from earlier PR:

- https://github.com/GovStackWorkingGroup/bb-identity/pull/35#discussion_r1218166177
- https://github.com/GovStackWorkingGroup/bb-identity/pull/35#discussion_r1218183454
- https://github.com/GovStackWorkingGroup/bb-identity/pull/35#discussion_r1218184325
- https://github.com/GovStackWorkingGroup/bb-identity/pull/35#discussion_r1218185056

2023-06-16 08:06 UTC, KarolinaKopacz requested changes

2023-06-16 08:06 UTC, KarolinaKopacz commented on test/openAPI/features/support/wallet_linked_authenticate.js
> +// Scenario: Not able to check the correctness of the data because of duplicated transactionId
Duplicated Scenario title

2023-06-16 08:34 UTC, KarolinaKopacz approved these changes

2023-06-26 02:00 UTC, vishwa-vyom requested changes

2023-06-26 02:00 UTC, vishwa-vyom commented on test/openAPI/features/wallet_linked_authenticate.feature
> +    When Send POST /linked-authorization/authenticate request with given requestTime, linkedTransactionId, individualId, "PIN" as invalidAuthFactorType, "password" as challenge, "alpha-numeric" as fo
this when statement is confusing, if this is for (https://github.com/GovStackWorkingGroup/bb-identity/pull/35#discussion_r1223796963) comment, then we need to give invalid password for the PIN auth factor and expect auth failed

2023-06-28 15:08 UTC, KarolinaKopacz approved these changes

2023-06-30 10:37 UTC, vishwa-vyom approved these changes
Feature file looks good and all comments resolved.

2023-06-30 10:39 UTC, merged